// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWusC9vtv7Qkf5WFRuqH_34n6NVAQo910',
    appId: '1:1016469357398:web:26a35cd408be8b602f4cf7',
    messagingSenderId: '1016469357398',
    projectId: 'snowmakers-e8560',
    authDomain: 'snowmakers-e8560.firebaseapp.com',
    storageBucket: 'snowmakers-e8560.appspot.com',
    measurementId: 'G-BR9T8Y2006',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmXVQiIRMonHAkKB4cZ9dqkv2O9QvgY7s',
    appId: '1:1016469357398:android:d5664197b64bbddb2f4cf7',
    messagingSenderId: '1016469357398',
    projectId: 'snowmakers-e8560',
    storageBucket: 'snowmakers-e8560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOpFBrT_g0cOJdCbMWEpvFi98JgzIBa-w',
    appId: '1:1016469357398:ios:8de734cd70139f652f4cf7',
    messagingSenderId: '1016469357398',
    projectId: 'snowmakers-e8560',
    storageBucket: 'snowmakers-e8560.appspot.com',
    iosClientId: '1016469357398-7e0cdil0b16q7otbgf76glauojtvh6c6.apps.googleusercontent.com',
    iosBundleId: 'com.snowmakersdev.snow',
  );

}